### PR TITLE
[Laravel 5] Merge 'setOption' with 'setCallback' to call function script any where

### PR DESCRIPTION
**Pull request by thienhung1989**
Merge callbacks into options.
Allow add function script by 'setOptions' any where.
function in TableTool: fnClick,....

You can add button or html into Datable.
Example I want add tag a in Column 2 by option 'aoColumns' More.
```php
 'aoColumns' => array(
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.short') ,
                    'mData' => 'code',
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::generals.titles.option') ,
                    'mData' => "function (o) {
                        return '<a href=/Produto/Detalhar/>' + 'More' + '</a>';
                    }",
                    'sClass' => 'text-center no-padding valign-middle',
                    'sWidth' => '60pt',
                    'bSearchable' => false,
                    'bSortable' => false
                ),
```
Example:
```php
Datatable::table()->setOptions(array(
            'orderMulti' => true,
            'sDom' => '<"row btn-toolbar"<"col-xs-6 btn-toolbar"lT><"col-xs-6"f>>tr<"row"<"col-xs-6"i><"col-xs-6"p>>',
            'oTableTools' => array(
                'sSwfPath' => asset('packages/thesis-gate/layout-master/assets/swf/copy_csv_xls.swf') ,
                'sRowSelect' => 'multi',
                'sRowSelector' => 'td:not(:last-child)',
                'aButtons' => array(
                    array(
                        'sExtends' => "select_all",
                        'sButtonText' => '<i class="fa fa-check-square-o"></i>',
                        'sButtonClass' => 'btn-sm',
                        'sToolTip' => trans("management-system::generals.buttons.select") ,
                    ) ,
                    array(
                        'sExtends' => 'select_none',
                        'sButtonText' => '<i class="fa fa-square-o"></i>',
                        'sButtonClass' => 'btn-sm',
                        'sToolTip' => trans("management-system::generals.buttons.deselect") ,
                    ) ,
                    array(
                        'sExtends' => 'text',
                        'sButtonText' => '<i class="fa fa-circle-thin"></i>',
                        'sButtonClass' => 'reload_table_group btn-sm',
                        'fnClick' => "function(event){
            alert('ok');
        }",
                        'sToolTip' => trans("management-system::generals.buttons.reload") ,
                    ) ,
                    array(
                        'sExtends' => 'collection',
                        'sButtonText' => '<i class="fa fa-angle-double-down"></i>',
                        'sButtonClass' => 'btn-sm',
                        'aButtons' => array(
                            'xls',
                            'copy'
                        )
                    ) ,
                )
            ) ,
            'aoColumns' => array(
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.id') ,
                    'sClass' => 'text-center',
                    'sWidth' => '30pt',
                    'aDataSort' => array(
                        0,
                        1
                    ) ,
                    'mData' => 'id'
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.name') ,
                    'aDataSort' => array(
                        1,
                        0
                    ) ,
                    'mData' => 'name'
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.short') ,
                    'mData' => 'code',
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::generals.titles.option') ,
                    'mData' => null,
                    'sClass' => 'text-center no-padding valign-middle',
                    'sWidth' => '60pt',
                    'bSearchable' => false,
                    'bSortable' => false,
                )
            ) ,
            'fnRowCallback' => 'function( nRow, aData, iDisplayIndex ) {
                $btn_edit = "<button class=\'btn btn-sm btn-default\' onclick=\'$(this).fnEdit(" + aData[\'id\'] + ")\'><i type=\'button\' class=\'glyphicon glyphicon-pencil text-green\' role=\'button\'></i></button>";
                $btn_delete = "<button class=\'btn btn-sm btn-default\' onclick=\'$(this).fnDelete(" + aData[\'id\'] + ")\'><i type=\'button\' class=\'glyphicon glyphicon-trash text-red\' role=\'button\'></i></button>";
                $("td:eq(3)", nRow).html($btn_edit + "&nbsp;" + $btn_delete);
            }',
            
            'infoCallback' => 'function( settings, start, end, max, total, pre ) {
                $(this).fnSetApi(this.api());
                $("td:eq(3)").
            }',
            
            'fnServerParams' => 'function(aoData) {
                aoData.push({name: "site_id", value: $(\'#site\').val()});
            }',
            'fnServerData' => "function ( sSource, aoData, fnCallback, oSettings ) {
        var oApi = this.oApi;
        aoData.push({ 'name': 'method', 'value': 'list'});
        oSettings.jqXHR = $.ajax( {
            'dataType': 'json',
            'type': 'POST',
            'url': sSource,
            'data': aoData,
            'success': fnCallback,
            'error': function( xhr, textStatus, error ){
              if ( textStatus === 'timeout' ) {
                alert( '" . trans('layout-master::datatables.titles.AjaxTimeOut') . "' );
              } else {
                alert( '" . trans('layout-master::datatables.titles.AjaxError') . "' );
              }
              oApi._fnProcessingDisplay( oSettings, false );
            },
            beforeSend: function(request) {
              return request.setRequestHeader('X-CSRF-Token', $(\"meta[name='csrf-token']\").attr('content'));
            }
        });
      }"
        ))->addColumn(array(
            trans('management-system::units.titles.id') ,
            trans('management-system::units.titles.name') ,
            trans('management-system::units.titles.short') ,
            trans('management-system::generals.titles.option') ,
        ))->setUrl(route('groups.postList'))->setId('table_group')->render();
```

Note: Can remove function 'setCallback' but i think use 'setCallback' still good and future will delete it!

### CODE REVIEW

**Comment by timgws** [comment]
Hey @thienhung1989. This branch is for Laravel 4. Can you please remove the commits for the updates to make it work with Laravel 5?

**Comment by thienhung1989** [comment]
@timgws ? 
About what? Sorry, I do not remember much.

**Comment by bytestream** [comment]
This breaks the setOptions and setCallback functions resulting in
````Method Illuminate\View\View::__toString() must not throw an exception````

Reverting back to the original ````javascript.blade.php```` file fixed the problem

**Comment by thienhung1989** [comment]
Thanks @bytestream,
Show me 'config' & 'response' you edited ?

In version current: 
- No remove Config:get(...) in config (because I edited path to translate any thing :) )

I hope you will feedback for me.

**Comment by thienhung1989** [comment]
If error sample `UnexpectedValueException in Response.php line 403: The Response content must be a string or object implementing __toString(), "object" given.`

You must add '->render()' in the last 'config of Datatable' when return.

**Comment by bytestream** [comment]
HI @thienhung1989,

I tried removing ```Config::get```  to no avail (in all 3 templates)

The following 'config' options result in the error - if I comment these out it loads fine:

    ->setOptions([
        'order' => [[ 0, 'asc' ]],
        'columnDefs' => [[
            "targets" => [ 0 ],
            "visible" => false,
            "searchable" => true
        ]]
    ])



    ->setCallbacks([
        'fnDrawCallback' => 'function() {
            tableDnd("' .  route('myroute', [ 'data' ]) . '");
        }',
        'fnRowCallback' => 'function(nRow, aData, iDisplayIndex) {
            $(nRow).attr("id", aData[1]);
            return nRow;
        }',
    ])

**Comment by bytestream** [comment]
@thienhung1989 you also have a number problem, callbacks are missing commas in between properties. For example:

    "fnDrawCallback": function() {
        tableDnd("...");
    }
    "fnRowCallback": function(nRow, aData, iDisplayIndex) {
        $(nRow).attr("id", aData[1]);
        return nRow;
    }

The callback foreach in ````options.blade.php```` and ````javascript.blade.php```` needs changing to:

    @foreach ($callbacks as $k => $o)
        {!! json_encode($k) !!}: {!! $o !!},
    @endforeach

Note the comma...

@Chumper please correct this also

**Comment by thienhung1989** [comment]
Hi, @bytestream 
- The first, you can merge 2 option to:
```php
->setOptions([
    'order' => [[ 0, 'asc' ]],
    'columnDefs' => [[
        "targets" => [ 0 ],
        "visible" => false,
        "searchable" => true
    ]],
    'fnDrawCallback' => 'function() {
        tableDnd("' .  route('myroute', [ 'data' ]) . '");
    }',
    'fnRowCallback' => 'function(nRow, aData, iDisplayIndex) {
        $(nRow).attr("id", aData[1]);
        return nRow;
    }',
])
```

Because I did skip option if value 'function' .... so, not need use 'setCallbacks'.

- Second, You just need remove 'config::get' in app/config/chumper.datatable.php. Orther, keep origin, don't edit if no need.

:)

**Comment by thienhung1989** [comment]
OK, I see missed comma...
Thanks @bytestream

**Comment by bytestream** [comment]
@thienhung1989 thanks for the heads up. Glad I don't need to edit ````vendor/````

**Comment by thienhung1989** [comment]
Just add `,` Thanks @bytestream.

@if ( $first == false ),@endif
@foreach ($callbacks as $k => $o) {{ json_encode($k) }}: {{ $o }},
@endforeach
});  

However, version current you merge setCallbacks into setConfigs, it still fine! I fix it soon. 
Good Luck.

**Pull request merged**
