### PR TITLE
Merge 'setOption' with 'setCallback' to call function script any where

### PR DESCRIPTION
**Pull request by thienhung1989**
Merge callbacks into options:
- Use 'setOptions' instead 'setCallbacks' *(of course, still use the function 'setCallbacks')*.
- Fix `function` *(js)* deep declare in array (when add by `setOptions`).
- Allow add function script by 'setOptions' any where.
 * function in TableTool: fnClick,....
 * You can add button or html into Datable.

- Example: I want add tag a in Column 2 by option 'aoColumns' More.
```php
 'aoColumns' => array(
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.short') ,
                    'mData' => 'code',
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::generals.titles.option') ,
                    'mData' => "function (o) {
                        return '<a href=/Produto/Detalhar/>' + 'More' + '</a>';
                    }",
                    'sClass' => 'text-center no-padding valign-middle',
                    'sWidth' => '60pt',
                    'bSearchable' => false,
                    'bSortable' => false
                ),
```
Example:
```php
Datatable::table()->setOptions(array(
            'orderMulti' => true,
            'sDom' => '<"row btn-toolbar"<"col-xs-6 btn-toolbar"lT><"col-xs-6"f>>tr<"row"<"col-xs-6"i><"col-xs-6"p>>',
            'oTableTools' => array(
                'sSwfPath' => asset('packages/thesis-gate/layout-master/assets/swf/copy_csv_xls.swf') ,
                'sRowSelect' => 'multi',
                'sRowSelector' => 'td:not(:last-child)',
                'aButtons' => array(
                    array(
                        'sExtends' => "select_all",
                        'sButtonText' => '<i class="fa fa-check-square-o"></i>',
                        'sButtonClass' => 'btn-sm',
                        'sToolTip' => trans("management-system::generals.buttons.select") ,
                    ) ,
                    array(
                        'sExtends' => 'select_none',
                        'sButtonText' => '<i class="fa fa-square-o"></i>',
                        'sButtonClass' => 'btn-sm',
                        'sToolTip' => trans("management-system::generals.buttons.deselect") ,
                    ) ,
                    array(
                        'sExtends' => 'text',
                        'sButtonText' => '<i class="fa fa-circle-thin"></i>',
                        'sButtonClass' => 'reload_table_group btn-sm',
                        'fnClick' => "function(event){
            alert('ok');
        }",
                        'sToolTip' => trans("management-system::generals.buttons.reload") ,
                    ) ,
                    array(
                        'sExtends' => 'collection',
                        'sButtonText' => '<i class="fa fa-angle-double-down"></i>',
                        'sButtonClass' => 'btn-sm',
                        'aButtons' => array(
                            'xls',
                            'copy'
                        )
                    ) ,
                )
            ) ,
            'aoColumns' => array(
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.id') ,
                    'sClass' => 'text-center',
                    'sWidth' => '30pt',
                    'aDataSort' => array(
                        0,
                        1
                    ) ,
                    'mData' => 'id'
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.name') ,
                    'aDataSort' => array(
                        1,
                        0
                    ) ,
                    'mData' => 'name'
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::units.titles.short') ,
                    'mData' => 'code',
                ) ,
                array(
                    
                    // 'sTitle' => trans('management-system::generals.titles.option') ,
                    'mData' => null,
                    'sClass' => 'text-center no-padding valign-middle',
                    'sWidth' => '60pt',
                    'bSearchable' => false,
                    'bSortable' => false,
                )
            ) ,
            'fnRowCallback' => 'function( nRow, aData, iDisplayIndex ) {
                $btn_edit = "<button class=\'btn btn-sm btn-default\' onclick=\'$(this).fnEdit(" + aData[\'id\'] + ")\'><i type=\'button\' class=\'glyphicon glyphicon-pencil text-green\' role=\'button\'></i></button>";
                $btn_delete = "<button class=\'btn btn-sm btn-default\' onclick=\'$(this).fnDelete(" + aData[\'id\'] + ")\'><i type=\'button\' class=\'glyphicon glyphicon-trash text-red\' role=\'button\'></i></button>";
                $("td:eq(3)", nRow).html($btn_edit + "&nbsp;" + $btn_delete);
            }',
            
            'infoCallback' => 'function( settings, start, end, max, total, pre ) {
                $(this).fnSetApi(this.api());
                $("td:eq(3)").
            }',
            
            'fnServerParams' => 'function(aoData) {
                aoData.push({name: "site_id", value: $(\'#site\').val()});
            }',
            'fnServerData' => "function ( sSource, aoData, fnCallback, oSettings ) {
        var oApi = this.oApi;
        aoData.push({ 'name': 'method', 'value': 'list'});
        oSettings.jqXHR = $.ajax( {
            'dataType': 'json',
            'type': 'POST',
            'url': sSource,
            'data': aoData,
            'success': fnCallback,
            'error': function( xhr, textStatus, error ){
              if ( textStatus === 'timeout' ) {
                alert( '" . trans('layout-master::datatables.titles.AjaxTimeOut') . "' );
              } else {
                alert( '" . trans('layout-master::datatables.titles.AjaxError') . "' );
              }
              oApi._fnProcessingDisplay( oSettings, false );
            },
            beforeSend: function(request) {
              return request.setRequestHeader('X-CSRF-Token', $(\"meta[name='csrf-token']\").attr('content'));
            }
        });
      }"
        ))->addColumn(array(
            trans('management-system::units.titles.id') ,
            trans('management-system::units.titles.name') ,
            trans('management-system::units.titles.short') ,
            trans('management-system::generals.titles.option') ,
        ))->setUrl(route('groups.postList'))->setId('table_group')->render();
```

### CODE REVIEW

**Comment by thienhung1989** [comment]
Fixed setCallbacks missed comma. 

:)

**Comment by thienhung1989** [comment]
Reformat *(view easy and remove something no need)*

**Comment by timgws** [comment]
I am not sure I agree 100% with the way that you are implementing your functionality for the datatables. 

I would try to keep the javascript code that you are writing inside your views, keeping them out of your controllers.

The best way to handle this (in my opinion) would be to create a new template (the name of which you would pass into `function render()`) where the javascript would live.

@thienhung1989 I have a function & some code that I have written that ads a simple templating system for rows, similar to what you have done here. I will clean up the code tonight and push it if you want to have a play.

**Comment by thienhung1989** [comment]
You're right. Of course, this is only a temporary solution.

**Comment by thienhung1989** [comment]
You're right. 

Of course, this is only my temporary solution. Because if you change it in the render function () when release code will be some sites do not work when they are using the old way (their template).

**Comment by thienhung1989** [comment]
```php
    private function convertData($options)
    {
        $is_obj = false;
        $first  = true;
        $data   = "";
        foreach ($options as $k => $o) {
            if ($first == true) {
                $is_obj = true;
                $first  = false;
            }
            if (!is_numeric($k)) {
                $data += json_encode($k) . ":";
            }
            if (is_string($o)) {
                if (@preg_match("#^\s*function\s*\([^\)]*#", $o)) {
                    $data += $o;
                } else {
                    $data += json_encode($o);
                }
            } else {
                if (is_array($o)) {
                    $this->convertData($o);
                } else {
                    $data += json_encode($o);
                }
            }
            $data += ",";
        }

        if ($is_obj) {
            $data = "{$data}";
        } else {
            $data = "[$data]";
        }

        return $data;
    }
    public function render($view = null)
    {
        if (!is_null($view)) {
            $this->table_view = $view;
        }

        if (!isset($this->options['sAjaxSource'])) {
            $this->setUrl(Request::url());
        }

        // create mapping for frontend
        if (!$this->createdMapping) {
            $this->createMapping();
        }

        return View::make($this->table_view, [
            'options'   => $this->convertData($this->options),
            'callbacks' => $this->convertData($this->callbacks),
            'values'    => $this->customValues,
            'data'      => $this->data,
            'columns'   => array_combine($this->aliasColumns, $this->columns),
            'noScript'  => $this->noScript,
            'id'        => $this->idName,
            'class'     => $this->className,
        ]);
```

in Template
```
<script type="text/javascript">
    jQuery(document).ready(function(){
        // dynamic table
        oTable = jQuery('#{!! $id !!}').dataTable({
            $options,
            $callbacks
        });
    });
</script>

```

@timgws

**Comment by timgws** [comment]
Yeah, that's cool. `$id` should never contain HTML-unsafe characters, so it should be fine to be leave with html encoding enabled (ie, use `{{` and `}}`).

With `$options` and `$callbacks` this might not be the case.

**Comment by thienhung1989** [comment]
Yes, i fixed

**Comment by thienhung1989** [comment]
#304 I Fixed!

**Pull request closed without merging**
